version: '0.1.0'

volumes:
  data:

services:
  postgredb:
    container_name: postgredb
    hostname: postgredb
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=password
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql

  react-dwp-service:
    image: dwpreact
    ports:
      - 3000
    depends_on:
      - battleships-service-1
      - postgredb

  dwp-service:
    container_name: dwp-service
    hostname: dwp-service
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      JDBC_DATABASE_URL: "jdbc:postgresql://postgredb:5432/postgres?user=postgres&password=postgres"
      SERVER_PORT: 8081
    ports:
      - 8081:8081
    depends_on:
      - postgredb

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - 8080:8080
    volumes:
      - ./:/etc/nginx
    depends_on:
      - react-dwp-service
      - dwp-service
