DROP TABLE IF EXISTS DocumentoProcesso cascade;
DROP TABLE IF EXISTS EtapaProcesso cascade;
DROP TABLE IF EXISTS UtilizadorPapel cascade;
DROP TABLE IF EXISTS UtilizadorEtapa cascade;
DROP TABLE IF EXISTS UtilizadorProcesso cascade;
DROP TABLE IF EXISTS ComentarioEtapa cascade;
DROP TABLE IF EXISTS ComentarioUtilizador cascade;
DROP TABLE IF EXISTS Comentario cascade;
DROP TABLE IF EXISTS Utilizador cascade;
DROP TABLE IF EXISTS Etapa cascade;
DROP TABLE IF EXISTS Processo cascade;
DROP TABLE IF EXISTS Documento cascade;
DROP TABLE IF EXISTS Papel cascade;
drop domain email;
drop domain alfanumeric_password;